### ISSUE TITLE
SSL error even with sslmode=disable

### ISSUE THREAD

**Issue by guenichone** [prometheus-community/postgres_exporter#1029]
**What did you do?**

I run the command to use the exporter on my local postgres database.

**What did you expect to see?**

A successful connection when prometheus try to fetch the data using the scrapper configuration.

**What did you see instead? Under which circumstances?**

I'm getting an pq SSL error. 

**Environment**

* System information:

Darwin 23.4.0 arm64

* postgres_exporter version:

postgres_exporter, version 0.15.0 (branch: HEAD, revision: 68c176b8833b7580bf847cecf60f8e0ad5923f9a)
  build user:       root@7c5a76bc737a
  build date:       20231027-14:38:04
  go version:       go1.21.3
  platform:         linux/arm64
  tags:             unknown

* postgres_exporter flags:

No flags, just the existing command to run the docker image:

docker run \
  --net=host \
  -e DATA_SOURCE_NAME='postgresql://postgres:password@localhost:5432/testdb?sslmode=disable' \
  prometheuscommunity/postgres-exporter:v0.15.0

* PostgreSQL version:

postgres (PostgreSQL) 13.2 (Debian 13.2-1.pgdg100+1)

* Logs:
```
ts=2024-05-07T20:13:43.114Z caller=probe.go:41 level=info msg="no auth_module specified, using default"
ts=2024-05-07T20:13:43.114Z caller=server.go:74 level=info msg="Established new database connection" fingerprint=localhost:5432
ts=2024-05-07T20:13:43.118Z caller=probe.go:81 level=error target=localhost:5432 msg="Error opening connection to database" err="error querying postgresql version: pq: SSL is not enabled on the server"
ts=2024-05-07T20:13:44.121Z caller=postgres_exporter.go:682 level=error err="Error opening connection to database (postgresql://localhost:5432): pq: SSL is not enabled on the server"
```

Prometheus scrap config:

```
scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:5432']
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9187  # The postgres exporter's real hostname:port.
```
