### ISSUE TITLE
`server` label is not added consistently to metrics

### ISSUE THREAD

**Issue by KulykDmytro** [prometheus-community/postgres_exporter#1030]
Hi

At 0.15 running for of RDS instance (in kubernetes) we observing following behaviour. on default settings + `queries.yaml`
These collectors provides `server` label, other not:
* all metrics passed over `queries.yaml`
* `pg_settings`
* `pg_stat_activity`
* `pg_stat_archiver`
* `pg_stat_database` (only for `conflicts_confl` section)
* `pg_static`

expected that labeling will be consistent (all on or all off) or at least configurable per collector

**Environment**

AWS EKS

* System information:

```bash
Linux 5.10.214-202.855.amzn2.x86_64 x86_64
```

* postgres_exporter version: 
```bash
postgres_exporter, version 0.15.0 (branch: HEAD, revision: 68c176b8833b7580bf847cecf60f8e0ad5923f9a)
  build user:       root@88f74f2c2888
  build date:       20231027-14:38:56
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             unknown
```

* postgres_exporter flags/variables:

```yaml
variables:
  PG_EXPORTER_EXCLUDE_DATABASES: rdsadmin
  PG_EXPORTER_EXTEND_QUERY_PATH: '/var/lib/postgresql/queries.yaml'
```

* PostgreSQL version: 14.10.0 (AWS RDS)
