### ISSUE TITLE
Feature Request: Allow Each Row to Become a Metric

### ISSUE THREAD

**Issue by eduardoap** [prometheus-community/postgres_exporter#1041]
Hello,

I have encountered a limitation that impacts my use case. Currently, the exporter only supports creating metrics from columns returned in the query results, and it assumes that only a single row is returned. Each column in this single row can be transformed into a metric.

However, I need the ability to create metrics from each row returned by a query. In other words, each row should be able to become a separate metric. This would greatly enhance the flexibility and usability of the exporter for more complex queries that return multiple rows of data.

Example Use Case:

Suppose we have a query that returns multiple rows, each representing different metrics:

```sql
SELECT
  metric_name,
  metric_description,
  metric_value
FROM
  my_table;
```

Proposed Solution:

Modify the exporter to iterate over each row returned by a query.
For each row, generate a metric using one column as the metric name and another as the metric value.
This enhancement would significantly improve the flexibility of the exporter, making it more useful for a wider range of queries and use cases.

Thank you for considering this feature request. I believe it will be a valuable addition to the project.

**Comment by eduardoap** [comment]
The feature is already available. So I'm closing this issue.


```yaml
    pg:
      query: |
         SELECT
           metric_name,
           metric_description,
           metric_value
         FROM
           my_table;
      metrics:
        - metric_name:
            usage: "LABEL"
            description: "Metric description"
        - metric_value:
            usage: "GAUGE"
            description: "Metric value"
```
