### ISSUE TITLE
Encrypted Backups: invalid input syntax for type json

### ISSUE THREAD

**Issue by cgmEdi** [prometheus-community/postgres_exporter#1062]
**What did you do?**
Using the posgres operator in versioncrunchydata/postgres-operator:ubi8-5.5.1-0
With a postgres cluster that uses the images

crunchydata/crunchy-pgbackrest:ubi8-2.40-1
crunchydata/crunchy-pgbouncer:ubi8-1.21-0
crunchydata/crunchy-postgres-exporter:ubi8-0.15.0-10 (same behavior in ubi8-0.15.0-0)
crunchydata/crunchy-postgres:ubi8-14.5-1

When enabling backup encryption as described here
https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/backups-disaster-recovery/backups#encryption

```
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: backup-encryption
      global:
        # REPO1
        repo1-retention-full: "2"
        repo1-retention-full-type: "count"
        repo1-cipher-type: aes-256-cbc
        repo1-path: ...
```

**What did you expect to see?**

I expected the exporter to send metadata about backups to grafana.

**What did you see instead? Under which circumstances?**

Instead i get no data in the grafana dashboards for backups and see the following errors in the exporter container (see logs).

**Environment**

* System information:

	Linux 5.15.0-89-generic x86_64

* postgres_exporter version:

  postgres_exporter, version 0.15.0 (branch: v0.15.0, revision: v0.15.0)
  build user:       
  build date:       2024-08-15T18:25:48Z
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             unknown

* postgres_exporter flags:
 The default flags that are confiugured in the image/operator.

* PostgreSQL version:
 14.5-1

* Logs:
```
ts=2024-09-02T08:55:38.016Z caller=namespace.go:236 level=info err="Error running query on database \"localhost:5432\": ccp_backrest_last_full_backup pq: invalid input syntax for type json"
ts=2024-09-02T08:55:38.044Z caller=namespace.go:236 level=info err="Error running query on database \"localhost:5432\": ccp_backrest_last_incr_backup pq: invalid input syntax for type json"
ts=2024-09-02T08:55:38.064Z caller=namespace.go:236 level=info err="Error running query on database \"localhost:5432\": ccp_backrest_last_info pq: invalid input syntax for type json"
ts=2024-09-02T08:55:38.088Z caller=namespace.go:236 level=info err="Error running query on database \"localhost:5432\": ccp_backrest_oldest_full_backup pq: invalid input syntax for type json"
ts=2024-09-02T08:55:38.118Z caller=namespace.go:236 level=info err="Error running query on database \"localhost:5432\": ccp_backrest_last_diff_backup pq: invalid input syntax for type json"
ts=2024-09-02T08:55:38.143Z caller=postgres_exporter.go:682 level=error err="queryNamespaceMappings returned 5 errors"
```
