### ISSUE TITLE
pg_stat_replication replication lag metrics do not work with logical replication slot

### ISSUE THREAD

**Issue by josharrington** [prometheus-community/postgres_exporter#484]
I have postgres_exporter installed on my postgres server connected over the unix socket. I have 2 physical replication slots and 2 logical replication slots (AWS DMS) pulling data from the master. Below, the 10.6.x.x ip addresses are physical, the 10.10.x.x ip addresses are logical:

```
# TYPE pg_stat_replication_pg_wal_lsn_diff gauge
pg_stat_replication_pg_wal_lsn_diff{application_name="",client_addr="10.10.11.46",server="/var/run/postgresql/:5432",slot_name="118347",state="streaming"} NaN
pg_stat_replication_pg_wal_lsn_diff{application_name="",client_addr="10.10.11.46",server="/var/run/postgresql/:5432",slot_name="118348",state="streaming"} NaN
pg_stat_replication_pg_wal_lsn_diff{application_name="12/main",client_addr="10.6.36.5",server="/var/run/postgresql/:5432",slot_name="1747",state="streaming"} 168848
pg_stat_replication_pg_wal_lsn_diff{application_name="12/main",client_addr="10.6.56.5",server="/var/run/postgresql/:5432",slot_name="49421",state="streaming"} 168848
```

I believe the reason boils down to the query below, located here: https://github.com/prometheus-community/postgres_exporter/blob/8531abac469ebb163ae9e4758e36d2ea9e6a3fcd/cmd/postgres_exporter/postgres_exporter.go#L395-L405

```
# SELECT client_addr,
    (case pg_is_in_recovery() when 't' then null else pg_current_wal_lsn() end) AS pg_current_wal_lsn,
    (case pg_is_in_recovery() when 't' then null else pg_wal_lsn_diff(pg_current_wal_lsn(), pg_lsn('0/0'))::float end) AS pg_current_wal_lsn_bytes,
    (case pg_is_in_recovery() when 't' then null else pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn)::float end) AS pg_wal_lsn_diff
   FROM pg_stat_replication;
 client_addr | pg_current_wal_lsn | pg_current_wal_lsn_bytes | pg_wal_lsn_diff
-------------+--------------------+--------------------------+-----------------
 10.10.11.46 | 23129/6C5EE000     |          617003934998528 |
 10.6.56.5   | 23129/6C5EE000     |          617003934998528 |          336192
 10.10.11.46 | 23129/6C5EE000     |          617003934998528 |
 10.6.36.5   | 23129/6C5EE000     |          617003934998528 |          336192
```

This query shows the write_lag and flush_lag correctly: 
```
# select client_addr,
         pg_wal_lsn_diff(sent_lsn, write_lsn) as write_lag,
         pg_wal_lsn_diff(sent_lsn, flush_lsn) as flush_lag,
         pg_wal_lsn_diff(sent_lsn, replay_lsn) as replay_lag
from pg_stat_replication;

 client_addr | write_lag | flush_lag | replay_lag
-------------+-----------+-----------+------------
 10.10.11.46 |  36353120 |  37394344 |
 10.6.56.5   |         0 |         0 |       1800
 10.10.11.46 |  22008568 |  22390400 |
 10.6.36.5   |         0 |         0 |       1800
```

I'm unsure if it is the case that logical replication does not populate replay_lsn explicitly or if this is just part of how AWS DMS works. We should probably add some additional stats to help with my use case: `pg_stat_replication_write_lag_bytes`, `pg_stat_replication_flush_lag_bytes`, `pg_stat_replication_replay_lag_bytes`.

**Comment by josharrington** [comment]
I've attempted to work around this but using a custom query. See below

queries.yaml:
```yaml
pg_replication_slot:
  query: |
    select pid, client_addr, state, sync_state,
         pg_wal_lsn_diff(sent_lsn, write_lsn) as write_lag,
         pg_wal_lsn_diff(sent_lsn, flush_lsn) as flush_lag,
         pg_wal_lsn_diff(sent_lsn, replay_lsn) as replay_lag
    from pg_stat_replication;
  master: true
  metrics:
    - client_addr:
        usage: "LABEL"
        description: "The replication client"
    - write_lag:
        usage: "GAUGE"
        description: "The write lag in bytes"
    - flush_lag:
        usage: "GAUGE"
        description: "The flush lag in bytes"
    - replay_lag:
        usage: "GAUGE"
        description: "The replay lag in bytes"
```

When I try to run this, I receive this error: 

```
* collected metric "pg_replication_slot_write_lag" { label:<name:"client_addr" value:"10.10.11.46" > label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:1.6193696e+07 > } was collected before with the same name and label values
* collected metric "pg_replication_slot_flush_lag" { label:<name:"client_addr" value:"10.10.11.46" > label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:1.6319256e+07 > } was collected before with the same name and label values
* collected metric "pg_replication_slot_replay_lag" { label:<name:"client_addr" value:"10.10.11.46" > label:<name:"server" value:"/var/run/postgresql/:5432" > gauge:<value:nan > } was collected before with the same name and label values
```

I attempted to use `master: true` and removing the `master` key but both produced the same result. I thought it might be related to autodiscovery based on some other reports but autodiscovery is not supported when using a unix socket (#476)
However, I run into an issue with db autodiscovery over a socket (#476). It seems that the `master` key is ignored when not using autodiscovery

**Comment by josharrington** [comment]
Oops! The queries.yaml above is bad since I have two replication slots sourcing from the same client and that caused the duplication error. I resolved that part by editing it like so:

```yaml
pg_replication_slot:
  query: |
    select pid, client_addr, state, sync_state,
         pg_wal_lsn_diff(sent_lsn, write_lsn) as write_lag,
         pg_wal_lsn_diff(sent_lsn, flush_lsn) as flush_lag,
         pg_wal_lsn_diff(sent_lsn, replay_lsn) as replay_lag
    from pg_stat_replication;
  master: true
  metrics:
    - pid:
        usage: "LABEL"
        description: "The pid of the process. Used to deduplicate the queries if multiple slots from the same client"
    - client_addr:
        usage: "LABEL"
        description: "The replication client"
    - write_lag:
        usage: "GAUGE"
        description: "The write lag in bytes"
    - flush_lag:
        usage: "GAUGE"
        description: "The flush lag in bytes"
    - replay_lag:
        usage: "GAUGE"
        description: "The replay lag in bytes"
```
