### ISSUE TITLE
Failed queries are not retried

### ISSUE THREAD

**Issue by deepak-auto** [prometheus-community/postgres_exporter#572]
**What did you do?**
Configured postgres_exporter to read from an RDS read replica. All the queries configured take less than 30 seconds, which is what `max_standby_archive_delay` and `max_standby_streaming_delay` are set to in PG. The queries have a cache period of 1 hour.

**What did you expect to see?**
The queries should finish successfully. In case they fail, they should be retried using a backoff.

**What did you see instead? Under which circumstances?**
I see multiple errors such as the following in the logs. Also, the metrics that show such errors are then missing from Prometheus. The query is only run again when the cache period expires.

**Environment**
* postgres_exporter version:

	Using helm chart version `2.3.5` that maps to version `v0.9.0` (https://github.com/prometheus-community/helm-charts/blob/cc8b7cb3d4f3c7445b56eeb91ca64340efdae2ed/charts/prometheus-postgres-exporter/values.yaml#L9)

* postgres_exporter flags:

```
  rbac:
    create: false
    pspEnabled: false
  readinessProbe:
    initialDelaySeconds: 180
  disableDefaultMetrics: true
  disableSettingsMetrics: true
```

* PostgresSQL version:
	11.5

* Logs:
```
time="2021-08-18T14:38:16Z" level=info msg="Error running query on database \"<DB_ADDRESS>\": <METRIC_NAME> pq: canceling statement due to conflict with recovery" source="postgres_exporter.go:1503"
time="2021-08-18T14:38:16Z" level=error msg="queryNamespaceMappings returned 1 errors" source="postgres_exporter.go:1621"
```
