### ISSUE TITLE
error: unknown long flag '--config.file'

### ISSUE THREAD

**Issue by KES777** [prometheus-community/postgres_exporter#709]
**What did you do?**
```
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    command: [
      "--config.file", "/etc/postgres-exporter.yml",
    ]
    volumes:
      - ${STACK_ROOT}/postgres-exporter.yml:/etc/postgres-exporter.yml
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@tsdb:5432/postgres?sslmode=disable"
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"
      PG_EXPORTER_EXCLUDE_DATABASES: "template0,template1"
      PG_EXPORTER_CONSTANT_LABELS: "dbcluster=pgdb"
```

**What did you expect to see?**
I expect, that `/etc/postgres-exporter.yml` was loaded.

**What did you see instead? Under which circumstances?**

```
postgres_exporter: error: unknown long flag '--config.file', try --help
```

**Environment**

* System information:
# docker compose version
Docker Compose version v2.12.2

* postgres_exporter version:
latest

* postgres_exporter flags:
```
  "--config.file", "/etc/postgres-exporter.yml",
```

* PostgreSQL version:
15.0.0

* Logs:
```
postgres_exporter: error: unknown long flag '--config.file', try --help
```

With `--help`:
```
usage: postgres_exporter [<flags>]

Flags:

  -h, --help                     Show context-sensitive help (also try

                                 --help-long and --help-man).

      --collector.database       Enable the database collector (default:

                                 enabled).

      --collector.bgwriter       Enable the bgwriter collector (default:

                                 enabled).

      --web.listen-address=":9187"  

                                 Address to listen on for web interface and

                                 telemetry.

      --web.config.file=""       [EXPERIMENTAL] Path to configuration file that

                                 can enable TLS or authentication.

      --web.telemetry-path="/metrics"  

                                 Path under which to expose metrics.

      --disable-default-metrics  Do not include default metrics.

      --disable-settings-metrics  

                                 Do not include pg_settings metrics.

      --auto-discover-databases  Whether to discover the databases on a server

                                 dynamically.

      --extend.query-path=""     Path to custom queries to run.

      --dumpmaps                 Do not run, simply dump the maps.

      --constantLabels=""        A list of label=value separated by comma(,).

      --exclude-databases=""     A list of databases to remove when

                                 autoDiscoverDatabases is enabled

      --include-databases=""     A list of databases to include when

                                 autoDiscoverDatabases is enabled

      --metric-prefix="pg"       A metric prefix can be used to have non-default

                                 (not "pg") prefixes for each of the metrics

      --version                  Show application version.

      --log.level=info           Only log messages with the given severity or

                                 above. One of: [debug, info, warn, error]

      --log.format=logfmt        Output format of log messages. One of: [logfmt,

                                 json]
```
