### ISSUE TITLE
Error parsing config file: line 2: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by KES777** [prometheus-community/postgres_exporter#710]
**What did you do?**
Configure auth_modules:
```
auth_modules:
  pgdb:
    type: userpass
    userpass:
      username: postgres
      password: password
    options:
      # options become key=value parameters of the DSN
      sslmode: disable

  tsdb:
    type: userpass
    userpass:
      username: postgres
      password: password
    options:
      # options become key=value parameters of the DSN
      sslmode: disable

```

**What did you expect to see?**
No errors.

**What did you see instead? Under which circumstances?**
```
err="Error parsing config file \"/etc/postgres-exporter.yml\": yaml: line 2: mapping values are not allowed in this context"
```

**Environment**
See here
* System information: docker compose

* postgres_exporter version: master

* postgres_exporter flags:

```
"--config.file", "/etc/postgres-exporter.yml",
```

* PostgreSQL version: 15.0.0

* Logs:
```
ts=2022-10-28T13:16:39.833Z caller=main.go:96 level=error msg="Error loading config" err="Error parsing config file \"/etc/postgres-exporter.yml\": yaml: line 2: mapping values are not allowed in this context"
```
