### ISSUE TITLE
exporter queries pg_settings, despite on it was disabled via `--disable-default-metrics`

### ISSUE THREAD

**Issue by KES777** [prometheus-community/postgres_exporter#712]
**What did you do?**
Disabled querying `pg_settings`
```
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:master
    command: [
      "--config.file", "/etc/postgres-exporter.yml",
      "--log.level", "debug",
      "--disable-default-metrics",
    ]
    volumes:
      - ${STACK_ROOT}/postgres-exporter.yml:/etc/postgres-exporter.yml
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:xxx@db:5432/postgres?sslmode=disable,postgresql://postgres:password@tsdb:5432/postgres?sslmode=disable"
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: "false"
      PG_EXPORTER_EXCLUDE_DATABASES: "template0,template1"
      PG_EXPORTER_CONSTANT_LABELS: "dbcluster=pgdb"
```

**What happened?**
I still see next at my logs:
```
ts=2022-10-28T20:19:59.974Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=db:5432
ts=2022-10-28T20:19:59.983Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=tsdb:5432
```

* postgres_exporter version: 0.12.0  / master
* postgres_exporter flags:

```
--disable-default-metrics
```

* Logs:
```
ts=2022-10-28T20:19:49.974Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=db:5432

ts=2022-10-28T20:19:49.980Z caller=postgres_exporter.go:617 level=debug msg="Querying PostgreSQL version" server=tsdb:5432

ts=2022-10-28T20:19:49.980Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=tsdb:5432

ts=2022-10-28T20:19:49.986Z caller=collector.go:190 level=debug msg="collector succeeded" name=database duration_seconds=0.014785915

ts=2022-10-28T20:19:59.973Z caller=collector.go:190 level=debug msg="collector succeeded" name=bgwriter duration_seconds=0.001673439

ts=2022-10-28T20:19:59.974Z caller=postgres_exporter.go:617 level=debug msg="Querying PostgreSQL version" server=db:5432

ts=2022-10-28T20:19:59.974Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=db:5432

ts=2022-10-28T20:19:59.980Z caller=collector.go:190 level=debug msg="collector succeeded" name=database duration_seconds=0.009202999

ts=2022-10-28T20:19:59.983Z caller=postgres_exporter.go:617 level=debug msg="Querying PostgreSQL version" server=tsdb:5432

ts=2022-10-28T20:19:59.983Z caller=pg_setting.go:35 level=debug msg="Querying pg_setting view" server=tsdb:5432
```

**Comment by KES777** [comment]
```
# cat postgres-exporter.yml 
auth_modules:
  pgdb:
    type: userpass
    userpass:
      username: postgres
      password: xxx
    options:
      # options become key=value parameters of the DSN
      sslmode: disable

  tsdb:
    type: userpass
    userpass:
      username: postgres
      password: password
    options:
      # options become key=value parameters of the DSN
      sslmode: disable
```
