### ISSUE TITLE
pg_stat_statements error on Postgres 15.1

### ISSUE THREAD

**Issue by warning-explosive** [prometheus-community/postgres_exporter#782]
**Problem**
Default metric 'queryNamespaceMappings' fails on Postgres 15.1
According to https://www.postgresql.org/docs/current/pgstatstatements.html pg_stat_statements in Postgres 15.1 doesn't have several columns from the script below
**logs from docker compose up**
```
...
postgres-exporter  | ts=2023-03-29T19:49:39.015Z caller=server.go:74 level=info msg="Established new database connection" fingerprint=postgres:5432
postgres-exporter  | ts=2023-03-29T19:49:39.045Z caller=postgres_exporter.go:647 level=info msg="Semantic version changed" server=postgres:5432 from=0.0.0 to=15.1.0
postgres           | 2023-03-29 19:49:39.062 UTC [84] ERROR:  column "total_time" does not exist at character 48
postgres           | 2023-03-29 19:49:39.062 UTC [84] STATEMENT:  SELECT t2.rolname, t3.datname, queryid, calls, total_time / 1000 as total_time_seconds, min_time / 1000 as min_time_seconds, max_time / 1000 as max_time_seconds, mean_time / 1000 as mean_time_seconds, stddev_time / 1000 as stddev_time_seconds, rows, shared_blks_hit, shared_blks_read, shared_blks_dirtied, shared_blks_written, local_blks_hit, local_blks_read, local_blks_dirtied, local_blks_written, temp_blks_read, temp_blks_written, blk_read_time / 1000 as blk_read_time_seconds, blk_write_time / 1000 as blk_write_time_seconds FROM pg_stat_statements t1 JOIN pg_roles t2 ON (t1.userid=t2.oid) JOIN pg_database t3 ON (t1.dbid=t3.oid) WHERE t2.rolname != 'rdsadmin'
postgres-exporter  | ts=2023-03-29T19:49:39.063Z caller=namespace.go:236 level=info err="Error running query on database \"postgres:5432\": pg_stat_statements pq: column \"total_time\" does not exist"
postgres-exporter  | ts=2023-03-29T19:49:39.075Z caller=postgres_exporter.go:716 level=error err="queryNamespaceMappings returned 1 errors"
...
```
**docker compose**
```
version: '3'
services:

  # PostgreSql
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    environment:
      - POSTGRES_PASSWORD=Password12!
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  # Postgres exporter
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.12.0
    container_name: postgres-exporter
    command:
      - --config.file=/etc/postgres-exporter/postgres-exporter.yaml
      - --extend.query-path=/etc/postgres-exporter/postgres-exporter-queries.yaml
    volumes:
      - ./postgres-exporter.yaml:/etc/postgres-exporter/postgres-exporter.yaml
      - ./postgres-exporter-queries.yaml:/etc/postgres-exporter/postgres-exporter-queries.yaml
    environment:
      - DATA_SOURCE_URI=postgres:5432?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=Password12!
    ports:
      - '9187:9187'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
```
**postgres-init.sql**
```
create extension if not exists pg_stat_statements;
create extension if not exists dblink;
```
**postgres-exporter.yaml**
```
auth_modules:
  postgres:
    type: userpass
    userpass:
      username: postgres
      password: Password12!
    options:
      sslmode: disable
```
**postgres-exporter-queries.yaml**
https://github.com/prometheus-community/postgres_exporter/blob/master/queries.yaml
