### ISSUE TITLE
Ease debugging of broken queries

### ISSUE THREAD

**Issue by samber** [prometheus-community/postgres_exporter#789]
## Proposal

Recently, I got stuck on a broken query that was executing against a removed table. I didn't identify such an error in staging (only in production) and could not find the query in our product code base. It took me hours to remember this request could have been used in our postgres_exporter.

In order to make the postgresql logs easier to troubleshoot, I would recommend to postgres_exporter to prefix queries with a short comment, such as:

```yaml
user_role:
  query: "SELECT role, COUNT(*) FROM users GROUP BY role;"
  metrics:
    - total:
        usage: "COUNTER"
        description: "Total users per role"
    - role:
        usage: "LABEL"
        description: "User role"
```

...would result in the following SQL queries:

```sql
--
-- Query executed by postgres_exporter (metric=user_role)
--
SELECT role, COUNT(*) FROM users GROUP BY role;
```
