### ISSUE TITLE
PG_EXPORTER_METRIC_PREFIX not working

### ISSUE THREAD

**Issue by zma-wtag** [prometheus-community/postgres_exporter#867]
Here is my configuration for the postgres-exporter in my docker-compose.yml (version 0.13.1)
```
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    command: --config.file=/etc/postgres_exporter/postgres_exporter.yml
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: postgresql://postgresUserName:postgresPassword@host.docker.internal:5432/mydb?sslmode=disable
      PG_EXPORTER_METRIC_PREFIX: 'myMetricsPrefix_'
    volumes:
      - ./docker/development/postgres_exporter.yml:/etc/postgres_exporter/postgres_exporter.yml
```
Output: 

```
# HELP pg_database_size_bytes Disk space used by the database
# TYPE pg_database_size_bytes gauge
pg_database_size_bytes{datname="mydb"} 1.1518755e+07
```

I expected to see `myMetricsPrefix_` instead of `pg`. Would anyone be able to help me out with this? 
on the other hand, there is no information regarding the `postgres_exporter.yml` configuration!
