### ISSUE TITLE
Inconsistent server label presence

### ISSUE THREAD

**Issue by mindw** [prometheus-community/postgres_exporter#883]
WIthout this label it is very troublesome to produce both dashboards and alerts based on the it. It cannot be added at the scrape config as the server address isn't passed to it. It can be done by a additional query - `pg_database_size_bytes* on(pod) group_left(server) pg_static{}`

**What did you do?**
Collected metrics from v12.x RDS postgres server.

**What did you expect to see?**
_all_ metrics having the `server` label.

**What did you see instead? Under which circumstances?**
Some metrics have them - the built in queries and those taken from queries.yaml, while internal and those produced by the collectors don't.
Adding constant labels (which is a deprecated feature for reason I could not find) only works for internal ones and built-ins. They are not applied to the new style collectors..

**Environment**

* System information:
Docker container running on EKS Kubernetes 1.26.
NO Multi target - it is not an option either.

* postgres_exporter version:
0.12.1 & 0.13.2

* postgres_exporter flags:

```yaml
        args:
        - --log.level=info
        - --no-collector.replication
        securityContext:
          runAsUser: 15001
        env:
        - name: DATA_SOURCE_URI
          value: <reducted>
        - name: DATA_SOURCE_USER
          value: postgres
        - name: PGPASSFILE
          value: "/postgres/.pgpass"
        - name: GOMAXPROCS
          value: "1"
        - name: GOMEMLIMIT
          value: "64Mib"
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: /config/queries.yaml
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"
        - name: PG_EXPORTER_EXCLUDE_DATABASES
          value: rdsadmin,template0,template1

```

* PostgreSQL version:

	12.6

* Logs:
nothing relevant - it seems to be a design error.
