### ISSUE TITLE
Cannot scrape postgres metrics

### ISSUE THREAD

**Issue by zxrmxn** [prometheus-community/postgres_exporter#932]
**What did you do?**
I'm trying to run postgres_exporter on Windows

**What did you expect to see?**
PostgreSQL Server Metrics Data

**What did you see instead? Under which circumstances?**
When I run the exporter I got a messages like below, I already add DATA_SOURCE_NAME on my config file but the log keep showing warning message about "empty dsn"
```
ts=2023-10-10T03:31:07.241Z caller=proc.go:250 msg="Excluded databases" databases=[]
ts=2023-10-10T03:31:07.241Z caller=main.go:142 level=warn msg="Failed to create PostgresCollector" err="empty dsn"
ts=2023-10-10T03:31:07.243Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9187
ts=2023-10-10T03:31:07.243Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9187
```

Below here is my config file, at first I'm not included DATA_SOURCE_NAME on my config file but same as the above I got an "empty dsn" message, so I thought I should include the DATA_SOURCE_NAME on the config file, but after I add the DATA_SOURCE_NAME the message I received is still the same
```
auth_modules:
  dvdrental:
    type: userpass
    userpass:
      username: postgres
      password: 'mypassword'
    options:
      DATA_SOURCE_NAME: postgresql://postgres:mypassword@localhost:5432/dvdrental?
      sslmode: disable
```
I know that the exporter is running because I can open http://localhost:9187/metrics, but there's no PostgreSQL metrics shown, Am I doing anything wrong?

**Environment**

* System information:

	OS: Windows 10 Pro 22H2

* postgres_exporter version:

	windows_exporter-0.24.0-amd64

* postgres_exporter flags:

```
--config.file=postgres_exporter.yml
```

* PostgreSQL version:

	postgresql-16.0-1-windows-x64
