### ISSUE TITLE
Connections leak in v0.14.0

### ISSUE THREAD

**Issue by Monstrofil** [prometheus-community/postgres_exporter#941]
**What did you do?**

I've added postgres_exporter container to my application as following:

```

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.14.0
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://...@postgres:5432/...?sslmode=disable"
    ports:
      - 9187:9187
```

**What did you expect to see?**

I expected postgres_exporter to use only couple of connections with postgresql to grab statistics.

**What did you see instead? Under which circumstances?**

I see postgres_exporter contantly using more and more connections with each scrape.

**Steps to reproduce**
- setup postgres and postgres_exporter containers
- run `ab -n 1000 -c 2 http://host:9187/metrics` to speed up things a little
- check pg_stat_database_numbackends metric, it will keep growing until reaches max_connections

We don't have this issue with v0.13.0, but we do have it with v0.14.0 and latest tags.
