### ISSUE TITLE
Add collector for pg_connections

### ISSUE THREAD

**Issue by guruguruguru** [prometheus-community/postgres_exporter#969]
## Proposal
**We had a query to count all connections by machine, which we lost due to deprecation of the queries file. I am sure others would profit from this as well**

```
pg_connections_by_machine:
  query: "select count(*) as count, client_hostname from pg_stat_activity where client_hostname is not null group by client_hostname ;"
  master: true
  metrics:
    - client_hostname:
        usage: "LABEL"
        description: "Name of connecting client"
    - count:
        usage: "GAUGE"
        description: "Number of Connections"
```
If there is another easy solution for this which I am missing right now please tell me.

Regards,
Dennis
