### ISSUE TITLE
Excluding database from collecting metric doesn't work

### ISSUE THREAD

**Issue by SergeiCherevko** [prometheus-community/postgres_exporter#982]
**What did you do?**

I tried to use
```
--exclude-databases name_db
```

**What did you expect to see?**

Stop collecting metrics from excluded db

**What did you see instead? Under which circumstances?**

```
postgres_exporter: error: unknown long flag '--exclude-databases healthbeat', try --help
```

**Environment**

```
version: '3.5'

services:
  pg_exporter:
    image: "bitnami/postgres-exporter:0.15.0"
    container_name: postgres_exporter
    hostname: postgres_exporter
    restart: unless-stopped
    network_mode: host
    command:
      - '--web.listen-address=:9630'
      - '--auto-discover-databases'
      - '--exclude-databases healthbeat'
    volumes:
      - /opt/pg_exporter/extra.yml:/opt/bitnami/postgres-exporter/extra.yml:ro
    environment:
      DATA_SOURCE_NAME: postgresql://{{ postgres_exporter }}:{{ postgres_exporter_password }}@{{ inventory_hostname }}:{{ postgres_port }}/{{ postgres_db }}?sslmode=disable
      PG_EXPORTER_EXTEND_QUERY_PATH: /opt/bitnami/postgres-exporter/extra.yml
```

* System information:

	Linux 6.2.0-1018-gcp x86_64

* postgres_exporter version:

	0.15.0

* postgres_exporter flags:

```
      - '--web.listen-address=:9630'
      - '--auto-discover-databases'
      - '--exclude-databases healthbeat'
```
* PostgreSQL version:

	14.10

* Logs:
```
postgres_exporter: error: unknown long flag '--exclude-databases healthbeat', try --help
```
